query sampleQuery {
    faroItemsByPlayUrn(
        urns: [
            "urn:srf:video:00025f95-2437-4dc3-a15a-44e5d2fa1d37",
            "urn:srf:video:f0076ff4-6f9a-48d8-a61c-83ad203b9f62"
        ]
    ) {
        producer
        program {
            department
        }
    }
}
